
//asval, Mk17 and SCAR-H arguable

private _categoryOverrideTable = [
["rhs_weap_vss", ["SniperRifles","Weapons"]],
["rhs_weap_vss_grip", ["SniperRifles","Weapons"]],
["rhs_weap_vss_npz", ["SniperRifles","Weapons"]],
["rhs_weap_vss_grip_npz", ["SniperRifles","Weapons"]],
["rhs_weap_svdp", ["SniperRifles","Weapons"]],
["rhs_weap_svdp_npz", ["SniperRifles","Weapons"]],
["rhs_weap_svdp_wd", ["SniperRifles","Weapons"]],
["rhs_weap_svdp_wd_npz", ["SniperRifles","Weapons"]],
["rhs_weap_svds", ["SniperRifles","Weapons"]],
["rhs_weap_svds_npz", ["SniperRifles","Weapons"]],
["rhs_weap_t5000", ["SniperRifles","Weapons"]],
["rhs_weap_pp2000", ["SMGs","Weapons"]],
["rhs_weap_XM2010", ["SniperRifles","Weapons"]],
["rhs_weap_XM2010_d", ["SniperRifles","Weapons"]],
["rhs_weap_XM2010_wd", ["SniperRifles","Weapons"]],
["rhs_weap_XM2010_sa", ["SniperRifles","Weapons"]],
["rhs_weap_m24sws", ["SniperRifles","Weapons"]],
["rhs_weap_m24sws_d", ["SniperRifles","Weapons"]],
["rhs_weap_m24sws_wd", ["SniperRifles","Weapons"]],
["rhs_weap_m40a5", ["SniperRifles","Weapons"]],
["rhs_weap_m40a5_d", ["SniperRifles","Weapons"]],
["rhs_weap_m40a5_wd", ["SniperRifles","Weapons"]],
["rhs_weap_M590_5RD", ["Shotguns","Weapons"]],
["rhs_weap_M590_8RD", ["Shotguns","Weapons"]],
["rhs_weap_kar98k", ["SniperRifles","Weapons"]],
["rhs_weap_m38", ["SniperRifles","Weapons"]],
["rhs_weap_m38_rail", ["SniperRifles","Weapons"]],
["rhs_weap_mosin_sbr", ["SniperRifles","Weapons"]],
["rhs_weap_mg42", ["MachineGuns","Weapons"]],
["rhs_weap_Izh18", ["Shotguns","Weapons"]],

["rhs_weap_M320", ["GrenadeLaunchers","Weapons"]],
["rhs_weap_m27iar", ["MachineGuns","Weapons"]],
["rhs_weap_m27iar_grip", ["MachineGuns","Weapons"]],
["rhs_weap_m32", ["GrenadeLaunchers","Weapons"]],
["rhs_weap_m79", ["GrenadeLaunchers","Weapons"]],

// These have a rifle grenade muzzle but with no magazines or wells defined
["rhs_weap_m70b1", ["Rifles","Weapons"]],
["rhs_weap_m70b1n", ["Rifles","Weapons"]],
["rhs_weap_m70ab2", ["Rifles","Weapons"]],

["B_rhsusf_B_BACKPACK", ["Unknown","Items"]],		// Drone backpack
["UK3CB_BAF_L103A2", ["Unknown","Items"]],			// Drill practice rifle, no mags

["UK3CB_Enfield", ["SniperRifles","Weapons"]],
["UK3CB_Enfield_rail", ["SniperRifles","Weapons"]],
["UK3CB_M14DMR", ["SniperRifles","Weapons"]],
["UK3CB_M21", ["SniperRifles","Weapons"]],
["UK3CB_SVD_OLD", ["SniperRifles","Weapons"]],
["UK3CB_M16A1_LSW", ["MachineGuns","Weapons"]],

["UK3CB_BAF_Javelin_Launcher", ["MissileLaunchers","Weapons","AT"]],
["UK3CB_BAF_Javelin_CLU", ["Binoculars","Items"]],
["UK3CB_BAF_Javelin_Slung_Tube", ["StaticWeaponParts","Items"]],
["UK3CB_M79", ["GrenadeLaunchers","Weapons"]],
["UK3CB_BAF_AT4_CS_AT_Launcher", ["RocketLaunchers","Weapons","AT"]],
["UK3CB_BAF_AT4_CS_AP_Launcher", ["RocketLaunchers","Weapons","AT"]],

["launch_NLAW_F", ["MissileLaunchers","Weapons","AT"]],
["hgun_PDW2000_F", ["SMGs","Weapons"]],

["UK3CB_BAF_L86A2", ["MachineGuns","Weapons"]],
["UK3CB_BAF_L86A3", ["MachineGuns","Weapons"]],

["UK3CB_BAF_Tripod", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L16_Tripod", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L111A1", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L134A1", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_L16", ["StaticWeaponParts","Items"]],
["UK3CB_BAF_M6", ["StaticWeaponParts","Items"]],

["UK3CB_M14_Rail", ["SniperRifles","Weapons"]],
["UK3CB_M21_Bipod_Railed", ["SniperRifles","Weapons"]],
["UK3CB_M14DMR_Railed", ["SniperRifles","Weapons"]],
["uk3cb_auga1_para", ["SMGs","Weapons"]],
["uk3cb_auga1_para_blk", ["SMGs","Weapons"]],
["uk3cb_auga1_para_tan", ["SMGs","Weapons"]],
["uk3cb_auga2_para", ["SMGs","Weapons"]],
["uk3cb_auga2_para_blk", ["SMGs","Weapons"]],
["uk3cb_auga2_para_tan", ["SMGs","Weapons"]],
["UK3CB_P90_black", ["SMGs","Weapons"]],
["UK3CB_P90_camo", ["SMGs","Weapons"]],
["UK3CB_P90_hex", ["SMGs","Weapons"]],
["UK3CB_P90_khaki", ["SMGs","Weapons"]],
["UK3CB_P90_TR_black", ["SMGs","Weapons"]],
["UK3CB_P90_TR_camo", ["SMGs","Weapons"]],
["UK3CB_P90_TR_hex", ["SMGs","Weapons"]],
["UK3CB_P90_TR_khaki", ["SMGs","Weapons"]],
["UK3CB_P90C_black", ["SMGs","Weapons"]],
["UK3CB_P90C_camo", ["SMGs","Weapons"]],
["UK3CB_P90C_hex", ["SMGs","Weapons"]],
["UK3CB_P90C_khaki", ["SMGs","Weapons"]],
["UK3CB_P90C_TR_black", ["SMGs","Weapons"]],
["UK3CB_P90C_TR_camo", ["SMGs","Weapons"]],
["UK3CB_P90C_TR_hex", ["SMGs","Weapons"]],
["UK3CB_P90C_TR_khaki", ["SMGs","Weapons"]],
["uk3cb_ppsh41", ["SMGs","Weapons"]],
["uk3cb_enfield_l8", ["SniperRifles","Weapons"]],
["uk3cb_enfield_l8_walnut", ["SniperRifles","Weapons"]],
["uk3cb_enfield_no3", ["SniperRifles","Weapons"]],
["uk3cb_enfield_no4", ["SniperRifles","Weapons"]],
["uk3cb_enfield_no4_walnut", ["SniperRifles","Weapons"]],
["uk3cb_enfield_no5", ["SniperRifles","Weapons"]],
["uk3cb_enfield_no5_walnut", ["SniperRifles","Weapons"]],
["UK3CB_CZ550", ["SniperRifles","Weapons"]],
["UK3CB_PSG1A1", ["SniperRifles","Weapons"]],
["UK3CB_PSG1A1_RIS", ["SniperRifles","Weapons"]],
["uk3cb_sks_01", ["SniperRifles","Weapons"]],
["uk3cb_sks_01_sling", ["SniperRifles","Weapons"]],
["uk3cb_sks_02", ["SniperRifles","Weapons"]],
["UK3CB_SVD_OLD_NPZ", ["SniperRifles","Weapons"]],
["UK3CB_MP5N_UGL", ["SMGs","Weapons","GrenadeLaunchers"]],
["uk3cb_auga1_hbar", ["MachineGuns","Weapons"]],
["uk3cb_auga1_hbar_tan", ["MachineGuns","Weapons"]],
["uk3cb_auga2_sr_hbar", ["MachineGuns","Weapons"]],
["uk3cb_auga2_sr_hbar_blk", ["MachineGuns","Weapons"]],
["uk3cb_auga2_sr_hbar_tan", ["MachineGuns","Weapons"]],
["UK3CB_G36_LSW", ["MachineGuns","Weapons"]],

["ace_csw_m3CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_m3CarryTripodLow", ["StaticWeaponParts","Items"]],
["ace_csw_kordCarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_kordCarryTripodLow", ["StaticWeaponParts","Items"]],
["ace_csw_m220CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_spg9CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_sag30CarryTripod", ["StaticWeaponParts","Items"]],
["ace_csw_carryMortarBaseplate", ["StaticWeaponParts","Items"]],
["ace_csw_staticATCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticAACarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticHMGCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticGMGCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticMortarCarry", ["StaticWeaponParts","Items"]],
["ace_csw_staticM2ShieldCarry", ["StaticWeaponParts","Items"]],

["ace_compat_rhs_afrf3_2b14_carry", ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_nsv_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_kord_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_ags30_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_spg9_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_spg9m_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_metis_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_afrf3_kornet_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_m252_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_m2_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_mk19_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_usf3_tow_carry" , ["StaticWeaponParts","Items"]],
["ace_compat_rhs_gref3_dshkm_carry" , ["StaticWeaponParts","Items"]],

["CUP_2b14_carry", ["StaticWeaponParts","Items"]],
["CUP_AGS30_carry" , ["StaticWeaponParts","Items"]],
["CUP_TOW_carry" , ["StaticWeaponParts","Items"]],
["CUP_TOW2_carry" , ["StaticWeaponParts","Items"]],
["CUP_DSHKM_carry" , ["StaticWeaponParts","Items"]],
["CUP_KORD_carry" , ["StaticWeaponParts","Items"]],
["CUP_m2_carry" , ["StaticWeaponParts","Items"]],
["CUP_m252_carry" , ["StaticWeaponParts","Items"]],
["CUP_MK19_carry" , ["StaticWeaponParts","Items"]],
["CUP_SPG9_carry" , ["StaticWeaponParts","Items"]],

["CUP_smg_bizon", ["SMGs","Weapons"]],
["CUP_smg_EVO", ["SMGs","Weapons"]],
["CUP_smg_M3A1_blk", ["SMGs","Weapons"]],
["CUP_smg_M3A1_grn", ["SMGs","Weapons"]],
["CUP_smg_M3A1_snd", ["SMGs","Weapons"]],
["CUP_smg_MP5A5", ["SMGs","Weapons"]],
["CUP_smg_MP5A5_Rail", ["SMGs","Weapons"]],
["CUP_smg_MP5A5_Rail_AFG", ["SMGs","Weapons"]],
["CUP_smg_MP5SD6", ["SMGs","Weapons"]],
["CUP_smg_MP7", ["SMGs","Weapons"]],
["CUP_smg_MP7_desert", ["SMGs","Weapons"]],
["CUP_smg_MP7_woodland", ["SMGs","Weapons"]],
["CUP_smg_SA61", ["SMGs","Weapons"]],
["CUP_smg_SA61_RIS", ["SMGs","Weapons"]],
["CUP_smg_saiga9", ["SMGs","Weapons"]],
["CUP_smg_vityaz", ["SMGs","Weapons"]],
["CUP_smg_vityaz_top_rail", ["SMGs","Weapons"]],
["CUP_smg_vityaz_vfg", ["SMGs","Weapons"]],
["CUP_smg_vityaz_vfg_front_rail", ["SMGs","Weapons"]],

["CUP_arifle_SAIGA_MK03", ["Shotguns","Weapons"]],
["CUP_arifle_SAIGA_MK03_top_rail", ["Shotguns","Weapons"]],
["CUP_arifle_SAIGA_MK03_Wood", ["Shotguns","Weapons"]],
["CUP_arifle_SIAGE_MK03_Wood_top_rail", ["Shotguns","Weapons"]],

["CUP_srifle_M2010_blk", ["SniperRifles","Weapons"]],
["CUP_srifle_M2010_ctrgt", ["SniperRifles","Weapons"]],
["CUP_srifle_M2010_dsrt", ["SniperRifles","Weapons"]],
["CUP_srifle_M2010_hex", ["SniperRifles","Weapons"]],
["CUP_srifle_M2010_wdl", ["SniperRifles","Weapons"]],
["CUP_srifle_M2010_winter", ["SniperRifles","Weapons"]],

["CUP_arifle_HK417_20", ["SniperRifles","Weapons"]],
["CUP_arifle_HK417_20_Desert", ["SniperRifles","Weapons"]],
["CUP_arifle_HK417_20_Wood", ["SniperRifles","Weapons"]],
["CUP_srifle_M14", ["SniperRifles","Weapons"]],
["CUP_srifle_M21", ["SniperRifles","Weapons"]],
["CUP_srifle_M21_ris", ["SniperRifles","Weapons"]],

["CUP_srifle_LeeEnfield", ["SniperRifles","Weapons"]],
["CUP_srifle_LeeEnfield_rail", ["SniperRifles","Weapons"]],
["CUP_srifle_Mosin_Nagant", ["SniperRifles","Weapons"]],

["CUP_arifle_MG36_hex", ["MachineGuns","Weapons"]],
["CUP_arifle_MG36", ["MachineGuns","Weapons"]],

["CUP_hgun_BallisticShield_Armed_M9", ["Unknown","Weapons"]],
["CUP_hgun_BallisticShield_PMM", ["Unknown","Weapons"]],
["CUP_smg_BallisticShield_MP7", ["Unknown","Weapons"]],
["CUP_smg_BallisticShield_PP19", ["Unknown","Weapons"]],
["CUP_smg_BallisticShield_Sa61", ["Unknown","Weapons"]],

["CUP_glaunch_6G30", ["GrenadeLaunchers","Weapons"]],
["CUP_glaunch_Mk13", ["GrenadeLaunchers","Weapons"]],
["CUP_glaunch_M32", ["GrenadeLaunchers","Weapons"]],

["CUP_launch_M136", ["RocketLaunchers","Weapons","AT"]],
["CUP_launch_NLAW", ["RocketLaunchers","Weapons","AT"]],

/*
// These work correctly now
["CUP_launch_FIM92Stinger", ["AA","Weapons"]],
["CUP_launch_Igla", ["AA","Weapons"]],
["CUP_launch_9K32Strela", ["MissileLaunchers","Weapons"]],
["CUP_launch_Metis", ["MissileLaunchers","Weapons"]],
["CUP_launch_Javelin", ["MissileLaunchers","Weapons"]],
*/

["CUP_item_Money", ["Unknown","Items"]],
["CUP_item_Kostey_photos", ["Unknown","Items"]],
["CUP_item_Kostey_map_case", ["Unknown","Items"]],
["CUP_item_Kostey_notebook", ["Unknown","Items"]],
["CUP_item_CDF_dogtags", ["Unknown","Items"]],
["CUP_item_Moscow_Bombing_File", ["Unknown","Items"]],
["CUP_item_Cobalt_File", ["Unknown","Items"]],

["ace_dragon_super", ["StaticWeaponParts","Items"]],
["ace_dragon_sight", ["Binoculars","Items"]],

["ACE_Kestrel4500", ["Gadgets","Items"]],
["ACE_ATragMX", ["Gadgets","Items"]],
["ACE_HuntIR_monitor", ["Gadgets","Items"]],
["ACE_microDAGR", ["Gadgets","Items"]],
["ACE_DAGR", ["Gadgets","Items"]],

["LIB_PTRD", ["Unknown", "Weapons"]],
["LIB_M2_Flamethrower", ["Unknown", "Weapons"]],			// don't want these two being chosen randomly by AIs
["LIB_Bagpipes", ["Unknown","Weapons"]],					// wat
["ACE_SatchelCharge_Remote_Mag_Throwable", ["Unknown", "Explosives", "Items"]],
["ACE_DemoCharge_Remote_Mag_Throwable", ["Unknown", "Explosives", "Items"]],
//Flashlights
["vn_mx991", ["Unknown","Weapons"]],
["vn_mx991_red", ["Unknown","Weapons"]],
["vn_fkb1_red", ["Unknown","Weapons"]],
["vn_fkb1", ["Unknown","Weapons"]],
["ACE_Flashlight_Maglite_ML300L", ["Unknown","Weapons"]],

["vn_default_helmetbase_09", ["Unknown","Headgear"]],	//Goat Hat
["vn_m1897", ["Shotguns","Weapons"]],
["vn_izh54", ["Shotguns","Weapons"]],
["vn_izh54_shorty", ["Shotguns","Weapons"]],
["vn_pps52", ["SMGs","Weapons"]],
["vn_pps43", ["SMGs","Weapons"]],
["vn_mc10", ["SMGs","Weapons"]],
["vn_ppsh41", ["SMGs","Weapons"]],
["vn_k50m", ["SMGs","Weapons"]],
["vn_mat49", ["SMGs","Weapons"]],
["vn_mat49_f", ["SMGs","Weapons"]],
["vn_mat49_vc", ["SMGs","Weapons"]],
["vn_m3a1", ["SMGs","Weapons"]],
["vn_sten", ["SMGs","Weapons"]],
["vn_mpu", ["SMGs","Weapons"]],
["vn_vz61", ["SMGs","Weapons"]],
["vn_m72", ["RocketLaunchers","Weapons","AT","Disposable"]],
["vn_m79", ["GrenadeLaunchers","Weapons"]],
["vn_sa7b", ["MissileLaunchers","Weapons","AA"]],
["vn_sa7", ["MissileLaunchers","Weapons","AA"]],
["vn_m2carbine", ["Rifles","Weapons"]],
["vn_m2carbine_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_m1carbine", ["Rifles","Weapons"]],
["vn_m1carbine_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_m3carbine", ["Rifles","Weapons"]],
["vn_m4956_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_sks_gl", ["Rifles","Weapons","GrenadeLaunchers"]],				// plain versions left as SniperRifles. This is fine
["vn_type56", ["Rifles","Weapons"]],
["vn_m63a_lmg", ["MachineGuns","Weapons"]],
["vn_m63a_cdo", ["MachineGuns","Weapons"]],
["vn_m127", ["Unknown","Weapons"]],								// flare launcher secondary
["vn_mk1_udg", ["Unknown","Weapons"]],							// underwater defence gun
["vn_m1_garand", ["Rifles","Weapons"]],
["vn_m1_garand_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_l1a1_01", ["Rifles","Weapons"]],
["vn_l1a1_01_camo", ["Rifles","Weapons"]],
["vn_l1a1_01_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_l1a1_02", ["Rifles","Weapons"]],
["vn_l1a1_02_camo", ["Rifles","Weapons"]],
["vn_l1a1_02_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_l1a1_03", ["Rifles","Weapons"]],
["vn_l1a1_03_camo", ["Rifles","Weapons"]],
["vn_l1a1_xm148", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_l1a1_xm148_camo", ["Rifles","Weapons","GrenadeLaunchers"]],
["vn_l2a1_01", ["MachineGuns","Weapons"]],
["vn_f1_smg", ["SMGs","Weapons"]],

//Unsung
["Uns_HMG", ["Unknown","Weapons"]],
["uns_m127a1_flare", ["Unknown","Weapons"]], // flare launcher secondary
["uns_ithaca37", ["Shotguns","Weapons"]],
["uns_ithaca37_grip", ["Shotguns","Weapons"]],
["uns_m1897", ["Shotguns","Weapons"]],
["uns_m1897riot", ["Shotguns","Weapons"]],
["uns_model12", ["Shotguns","Weapons"]],
["uns_baikal", ["Shotguns","Weapons"]],
["uns_baikal_sawnoff", ["Shotguns","Weapons"]],
["uns_m870", ["Shotguns","Weapons"]],
["uns_m870_mk1", ["Shotguns","Weapons"]],
["uns_M16A1_HBAR", ["MachineGuns","Weapons"]],
["uns_M63a_drum", ["MachineGuns","Weapons"]],
["uns_M63a_LMG", ["MachineGuns","Weapons"]],
["uns_m63asupport", ["MachineGuns","Weapons"]],
["uns_akms_drum", ["MachineGuns","Weapons"]],
["uns_akmsf_drum", ["MachineGuns","Weapons"]],
["uns_akm_drum", ["MachineGuns","Weapons"]],
["uns_m79", ["GrenadeLaunchers","Weapons"]],
["uns_ex41", ["GrenadeLaunchers","Weapons"]],
["uns_STG_44", ["Rifles","Weapons"]],
["uns_akmsf", ["Rifles","Weapons"]],
["uns_akms", ["Rifles","Weapons"]],
["uns_akm", ["Rifles","Weapons"]],
["uns_ak47_52", ["Rifles","Weapons"]],
["uns_ak47_49", ["Rifles","Weapons"]],
["uns_sa58vf", ["Rifles","Weapons"]],
["uns_sa58v", ["Rifles","Weapons"]],
["uns_sa58p_camo", ["Rifles","Weapons"]],
["uns_sa58p", ["Rifles","Weapons"]],
["uns_type56", ["Rifles","Weapons"]],
["uns_aks47f", ["Rifles","Weapons"]],
["uns_aks47", ["Rifles","Weapons"]],
["uns_ak47", ["Rifles","Weapons"]],
["uns_m1carbine", ["Rifles","Weapons"]],
["uns_m1carbine_pouch", ["Rifles","Weapons"]],
["uns_m1carbine_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_m1carbine_pouch_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_m2carbine", ["Rifles","Weapons"]],
["uns_m2carbine_shorty", ["Rifles","Weapons"]],
["uns_m2carbine_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_m3carbine", ["Rifles","Weapons"]],
["uns_m1garand", ["Rifles","Weapons"]],
["uns_m1garand_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_m14", ["Rifles","Weapons"]],
["uns_l1a1", ["Rifles","Weapons"]],
["uns_l1a1_enfield", ["Rifles","Weapons"]],
["uns_l1a1_blk", ["Rifles","Weapons"]],
["uns_l2a1", ["Rifles","Weapons"]],
["uns_l2a1_shorty", ["Rifles","Weapons"]],
["uns_l1a1gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_sks", ["Rifles","Weapons"]],
["uns_mas36", ["Rifles","Weapons"]],
["uns_mas36_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_mas36short", ["Rifles","Weapons"]],
["uns_mas36short_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_type99", ["Rifles","Weapons"]],
["uns_type99_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_mas4956", ["Rifles","Weapons"]],
["uns_mas4956_gl", ["Rifles","Weapons","GrenadeLaunchers"]],
["uns_m72", ["RocketLaunchers","Weapons","AT","Disposable"]],
["uns_m72used", ["UsedLaunchers","Weapons"]],

//ACRE Radios
//Using Gadgets instead of Radios to prevent future issues as they don't use the Radio Slot
["ACRE_PRC148", ["Gadgets","items"]],
["ACRE_PRC152", ["Gadgets","items"]],
["ACRE_PRC343", ["Gadgets","items"]],
["ACRE_PRC77", ["Gadgets","items"]],
["ACRE_SEM52SL", ["Gadgets","items"]],
["ACRE_SEM70", ["Gadgets","items"]],
["ACRE_VHF30108SPIKE", ["Gadgets","items"]],
["ACRE_VHF30108", ["Gadgets","items"]],
["ACRE_VHF30108MAST", ["Gadgets","items"]],
["ACRE_PRC117F", ["Gadgets","items"]],

["LIB_M2_Tripod", ["StaticWeaponParts","Items"]],
["LIB_Laffete_Tripod", ["StaticWeaponParts","Items"]],
["LIB_BM37_Tripod", ["StaticWeaponParts","Items"]],
["LIB_BM37_Barrel", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Tripod", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Tripod_g", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Barrel", ["StaticWeaponParts","Items"]],
["LIB_GrWr34_Barrel_g", ["StaticWeaponParts","Items"]],
["LIB_M2_60_Tripod", ["StaticWeaponParts","Items"]],
["LIB_M2_60_Barrel", ["StaticWeaponParts","Items"]],

//GM wrong listed stuff
["gm_m72a3_oli", ["RocketLaunchers","Weapons","AT","Disposable"]],
["gm_m72a3_spent_oli", ["UsedLaunchers","Weapons"]],
["gm_fim43_oli",["MissileLaunchers","Weapons","AA","Disposable"]],
["gm_fim43_spent_oli", ["UsedLaunchers","Weapons"]],
["gm_9k32m_oli", ["MissileLaunchers","Weapons","AA","Disposable"]],
["gm_9k32m_spent_oli", ["UsedLaunchers","Weapons"]],

["gm_mp2a1_blk",["SMGs","Weapons"]],
["gm_rpk_wud",["MachineGuns","Weapons"]],
["gm_lmgrpk_brn",["MachineGuns","Weapons"]],
["gm_lmgrpk_prp",["MachineGuns","Weapons"]],
["gm_lmgrpk74n_brn",["MachineGuns","Weapons"]],
["gm_lmgrpk74n_prp",["MachineGuns","Weapons"]],
["gm_g3a4_ebr_oli",["SniperRifles","Weapons"]],
["gm_g3a4_ebr_blk",["SniperRifles","Weapons"]],
["gm_g3a4_ebr_des",["SniperRifles","Weapons"]],
["gm_g3a3_dmr_oli",["SniperRifles","Weapons"]],
["gm_g3a3_dmr_blk",["SniperRifles","Weapons"]],
["gm_g3a3_dmr_des",["SniperRifles","Weapons"]],
["gm_svd_wud",["SniperRifles","Weapons"]],
["gm_hk69a1_blk", ["GrenadeLaunchers","Weapons"]],
["gm_pallad_d_brn", ["GrenadeLaunchers","Weapons"]],

//SPE

["SPE_Laffete_Tripod", ["StaticWeaponParts","Items"]],
["SPE_M1_81_Barrel", ["StaticWeaponParts","Items"]],
["SPE_MLE_27_31_Barrel", ["StaticWeaponParts","Items"]],
["SPE_M1_81_Stand", ["StaticWeaponParts","Items"]],
["SPE_GrW278_1_Stand", ["StaticWeaponParts","Items"]],
["SPE_M2_Tripod", ["StaticWeaponParts","Items"]],
["SPE_GrW278_1_Barrel", ["StaticWeaponParts","Items"]],
["SPE_MLE_27_31_Stand", ["StaticWeaponParts","Items"]],
["SPE_Flammenwerfer41", ["Unknown", "Weapons"]],
["SPE_M2_Flamethrower", ["Unknown", "Weapons"]],
["SPE_K98_GW", ["Rifles","Weapons","GrenadeLaunchers"]],
["SPE_K98_Late_GW", ["Rifles","Weapons","GrenadeLaunchers"]],
["SPE_M1903A3_Springfield_M1_GL", ["Rifles","Weapons","GrenadeLaunchers"]],
["SPE_M1_Carbine_M8", ["Rifles","Weapons","GrenadeLaunchers"]],
["SPE_M1_Garand_M7", ["Rifles","Weapons","GrenadeLaunchers"]] ];


//Create a local namespace.
A3A_categoryOverrides = false call A3A_fnc_createNamespace;
{
	A3A_categoryOverrides setVariable [_x select 0, _x select 1];
} forEach _categoryOverrideTable;
