name = "Antistasi Ultimate";
logo = "\x\A3A\addons\core\Pictures\antistasi_ultimate_logo_sw.paa";
logoOver = "\x\A3A\addons\core\Pictures\antistasi_ultimate_logo.paa";
logoSmall = "\x\A3A\addons\core\Pictures\antistasi_ultimate_logo_small.paa";
picture = "\x\A3A\addons\core\Pictures\antistasi_ultimate_overview.paa";
author = "Antistasi Ultimate Team, Socrates, Offical Antistasi Community";
description = "";
tooltip = "Antistasi Ultimate";
tooltipOwned = "Antistasi Ultimate";
overview = "<br/><t align='center' size='0.75'> An Arma 3 persistent multiplayer scenario about guerilla warfare tactics. Fork of Antistasi Plus Version focused on expanding templates, maps and features. </t><br/><br/>";
actionName = "GitHub";
action = "https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate";
hideName = 0;
hidePicture = 0;
dlcColor[] = {0.1765, 0.6392, 0.6235, 1};
