class mapInfo {
    #include "Antistasi_Altis.Altis\mapInfo.hpp"
    #include "Antistasi_Malden.Malden\mapInfo.hpp"
    #include "Antistasi_SefrouRamal.SefrouRamal\mapInfo.hpp"
    #include "Antistasi_Stratis.Stratis\mapInfo.hpp"
    #include "Antistasi_cup_chernarus_A3.cup_chernarus_A3\mapInfo.hpp"
    #include "Antistasi_Enoch.Enoch\mapInfo.hpp"
    #include "Antistasi_Esseker.Esseker\mapInfo.hpp"
    #include "Antistasi_Napf.Napf\mapInfo.hpp"
    #include "Antistasi_blud_vidda.blud_vidda\mapInfo.hpp"
    #include "Antistasi_vt7.vt7\mapInfo.hpp"
    #include "Antistasi_takistan.takistan\mapInfo.hpp"
    #include "Antistasi_Tanoa.Tanoa\mapInfo.hpp"
    #include "Antistasi_cam_lao_nam.cam_lao_nam\mapInfo.hpp"
    #include "Antistasi_vn_khe_sanh.vn_khe_sanh\mapInfo.hpp"
    #include "Antistasi_Sehreno.Sehreno\mapInfo.hpp"
    #include "Antistasi_gm_weferlingen_summer.gm_weferlingen_summer\mapInfo.hpp"
};
