    class FWA_unlimited_base : forbidden_unlimited_base {
        addons[] = {"sp_fwa_fal"};
    };
    
    class sp_fwa_ar18 : FWA_unlimited_base {};
    class sp_fwa_ar18_shorty : FWA_unlimited_base {};
    class sp_fwa_ar18_carbine : FWA_unlimited_base {};
    class sp_fwa_bm59_mk3_alpine : FWA_unlimited_base {};
    class sp_fwa_m1919a4_browning : FWA_unlimited_base {};
    class sp_fwa_m1919a6_browning : FWA_unlimited_base {};
    class sp_fwa_ar15_603_m16a1_captured : FWA_unlimited_base {};
    class sp_fwa_ar15_705_m16a2_m203 : FWA_unlimited_base {};
    class sp_fwa_ar15_646_m16a3_m203 : FWA_unlimited_base {};
    class sp_fwa_fal_m2 : FWA_unlimited_base {};
    class sp_fwa_fal_dutch : FWA_unlimited_base {};
    class sp_fwa_fal_g1 : FWA_unlimited_base {};
    class sp_fwa_falo_factory_50_41_bipod : FWA_unlimited_base {};
    class sp_fwa_falo_factory_50_42_bipod : FWA_unlimited_base {};
    class sp_fwa_fal_factory_50_00 : FWA_unlimited_base {};
    class sp_fwa_fal_factory_50_63 : FWA_unlimited_base {};
    class sp_fwa_fal_factory_50_64 : FWA_unlimited_base {};
    class sp_fwa_fn_modelDA1 : FWA_unlimited_base {};
    class sp_fwa_fal_stg58_fn : FWA_unlimited_base {};
    class sp_fwa_fal_t48_early : FWA_unlimited_base {};
    class sp_fwa_fal_t48_late : FWA_unlimited_base {};
    class sp_fwa_fal_t48_falo_bipod : FWA_unlimited_base {};
    class sp_fwa_fal_imbel_50_00 : FWA_unlimited_base {};
    class sp_fwa_fal_imbel_50_63 : FWA_unlimited_base {};
    class sp_fwa_sig510 : FWA_unlimited_base {};
    class sp_fwa_sig510_3 : FWA_unlimited_base {};
    class sp_fwa_sig510_4 : FWA_unlimited_base {};
    class sp_fwa_fal_stg58_steyr : FWA_unlimited_base {};
    class sp_fwa_2InchMortar : FWA_unlimited_base {};