CONDITION_DEBUG = False

CONDITION_COMMON_TRUE = "true"
CONDITION_COMMON_FALSE = "false"

CONDITION_COMMON_OR_START = "("
CONDITION_COMMON_OR_END = ")"
CONDITION_COMMON_START = "{"
CONDITION_COMMON_END = "}"
CONDITION_COMMON_OR = "||"
CONDITION_COMMON_AND = "&&"
CONDITION_COMMON_ZONES = f"call A3U_fnc_sidesX"

CONDITION_FUNCTION_REQUIREMENTS = f"A3U_fnc_hasRequirements"

CONDITION_TIER_LIGHT = f'["warlevel_3"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_TIER_MEDIUM = f'["warlevel_6"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_TIER_HEAVY = f'["warlevel_9"] call {CONDITION_FUNCTION_REQUIREMENTS}'

CONDITION_RESOURCE_LIGHT = f'["resources_1"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_RESOURCE_MEDIUM = f'["resources_2"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_RESOURCE_HEAVY = f'["resources_3"] call {CONDITION_FUNCTION_REQUIREMENTS}'

CONDITION_FACTORY_LIGHT = f'["factories_1"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_FACTORY_MEDIUM = f'["factories_2"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_FACTORY_HEAVY = f'["factories_3"] call {CONDITION_FUNCTION_REQUIREMENTS}'

CONDITION_MILBASE_LIGHT = f'["milbases_1"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_MILBASE_MEDIUM = f'["milbases_2"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_MILBASE_HEAVY = f'["milbases_3"] call {CONDITION_FUNCTION_REQUIREMENTS}'

CONDITION_AIRPORT_LIGHT = f'["airports_1"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_AIRPORT_MEDIUM = f'["airports_2"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_AIRPORT_HEAVY = f'["airports_3"] call {CONDITION_FUNCTION_REQUIREMENTS}'

CONDITION_SEAPORT_LIGHT = f'["seaports_1"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_SEAPORT_MEDIUM = f'["seaports_2"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_SEAPORT_HEAVY = f'["seaports_3"] call {CONDITION_FUNCTION_REQUIREMENTS}'

CONDITION_OUTPOST_LIGHT = f'["outposts_1"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_OUTPOST_MEDIUM = f'["outposts_3"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_OUTPOST_HEAVY = f'["outposts_5"] call {CONDITION_FUNCTION_REQUIREMENTS}'
CONDITION_OUTPOST_GIGANTIC = f'["outposts_10"] call {CONDITION_FUNCTION_REQUIREMENTS}'

# USAGE:
# print(f"{CONDITION_COMMON_OR_START}{CONDITION_SEAPORT_LIGHT} {CONDITION_COMMON_OR} {CONDITION_RESOURCE_MEDIUM}{CONDITION_COMMON_OR_END} {CONDITION_COMMON_AND} {CONDITION_FACTORY_MEDIUM}")
# RETURN:
# ({sidesX getVariable [_x,sideUnknown] isEqualTo teamPlayer} count seaports >= 1 || {sidesX getVariable [_x,sideUnknown] isEqualTo teamPlayer} count resourcesX >= 3) && {sidesX getVariable [_x,sideUnknown] isEqualTo teamPlayer} count factories >= 3