class vehicles_braf : vehicles_base
{
    ITEM(braf_guarani_eb_remax, 10740, "APC", VEHICLE_CONDITION_APC);
    ITEM(BRAF_AM11_Armed, 2200, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(BRAF_LMV_EB_RCWS, 9800, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(BRAF_EE9_Cascavel_EB, 28500, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(BRAF_AM11_Unarmed, 850, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(BRAF_LMV_EB, 1080, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
