class vehicles_3cbbaf : vehicles_base
{
    ITEM(UK3CB_BAF_FV432_Mk3_GPMG_Green_MTP, 7700, "APC", VEHICLE_CONDITION_APC);
    ITEM(UK3CB_BAF_FV432_Mk3_RWS_Green_MTP, 13600, "APC", VEHICLE_CONDITION_APC);
    ITEM(UK3CB_BAF_Coyote_Passenger_L111A1_W_MTP, 5600, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Coyote_Passenger_L134A1_W_MTP, 9200, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Jackal2_L2A1_W_MTP, 5600, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Jackal2_GMG_W_MTP, 9200, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Husky_Passenger_HMG_Green_MTP, 4800, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Husky_Passenger_GPMG_Green_MTP, 2600, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Husky_Passenger_GMG_Green_MTP, 9420, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_LandRover_WMIK_Milan_FFR_Green_A_MTP, 8500, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_LandRover_WMIK_HMG_FFR_Green_A_MTP, 4600, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_LandRover_WMIK_GPMG_FFR_Green_A_MTP, 2000, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_LandRover_WMIK_GMG_FFR_Green_A_MTP, 8200, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Panther_GPMG_Green_A_MTP, 5500, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(UK3CB_BAF_Static_L111A1_Deployed_Low_MTP, 3600, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(UK3CB_BAF_Static_L134A1_Deployed_High_MTP, 7200, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(UK3CB_BAF_Static_L134A1_Deployed_Low_MTP, 7200, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(UK3CB_BAF_Static_L134A1_Deployed_Mid_MTP, 7200, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(UK3CB_BAF_Static_L7A2_Deployed_High_MTP, 3600, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(UK3CB_BAF_Static_L7A2_Deployed_Low_MTP, 3600, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(UK3CB_BAF_Static_L7A2_Deployed_Mid_MTP, 3600, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(UK3CB_BAF_Static_M6_Deployed_MTP, 8000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);
    ITEM(UK3CB_BAF_Static_L16_Deployed_MTP, 8000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);
    ITEM(UK3CB_BAF_MQ9_Reaper_Generic_DDPM, 31400, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(UK3CB_BAF_LandRover_Panama_Green_A_MTP, 5500, "UAV", VEHICLE_CONDITION_UAV);
};
