class vehicles_tfc : vehicles_base
{
    ITEM(TFC_Wheeled_Bison_Amb, 6400, "APC", VEHICLE_CONDITION_APC);
    ITEM(TFC_Wheeled_Bison_CP, 2560, "APC", VEHICLE_CONDITION_APC);
    ITEM(tfc_wheeled_lav6_isc, 23720, "APC", VEHICLE_CONDITION_APC);
    ITEM(tfc_wheeled_lav6_lrss, 28240, "APC", VEHICLE_CONDITION_APC);
    ITEM(tfc_vs_luvw_armed_f, 2800, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(tfc_mrzr4_d_tow, 14100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(tfc_tapv_gmg, 18100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(TFC_BGM_71_Tripod, 9000, "STATICAT", VEHICLE_CONDITION_STATICAT);
    ITEM(tfc_ws_c16_gmg, 6000, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(TFC_MBT_Leopard2A4M_F, 44900, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(tfc_vs_luvw_f, 960, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
