class vehicles_wm : vehicles_base
{
    ITEM(WM_ITT_Imperial, 15040, "APC", VEHICLE_CONDITION_APC);
    ITEM(WM_AAC_Speeder, 13000, "APC", VEHICLE_CONDITION_APC);
    ITEM(WM_AAC_Speeder_Rocket, 19000, "APC", VEHICLE_CONDITION_APC);
    ITEM(WM_74Z_Imperial_Brown, 4000, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(WM_V25_Speeder, 5100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(WM_AAC_Speeder_Artillery, 40260, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    ITEM(WM_Tiefighter, 44500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(WM_TieDefender, 81500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(WM_TieInterceptor, 47000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(WM_TieAdvanced, 79000, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(WM_TieBomber, 46500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(WM_Lambda, 47700, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(WM_PTower, 6000, "STATICAT", VEHICLE_CONDITION_STATICAT);
    ITEM(WM_DF9, 5400, "STATICMG", VEHICLE_CONDITION_STATICMG);
    ITEM(WM_ATST, 49600, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(WM_ATAT, 73100, "TANK", VEHICLE_CONDITION_TANK);
};
