class vehicles_tmt : vehicles_base
{
    ITEM(TMT_Landrover_w_AA, 41000, "AA", VEHICLE_CONDITION_AA);
    ITEM(TMT_ACV300_W_Amb, 6320, "APC", VEHICLE_CONDITION_APC);
    ITEM(TMT_ACV300_W_M2, 5940, "APC", VEHICLE_CONDITION_APC);
    ITEM(TMT_KirpiII_MRAP_W, 13300, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(TMT_Cobra_RCWS_W, 9550, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(TMT_Ejder_RCWS_GEN, 12550, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(TMT_Arma_GMG_HMG, 18850, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(TMT_T155_W, 55800, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    ITEM(TMT_LEO2A4_w, 37100, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(TMT_Leopard2_NG_W, 46900, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(TMT_BayraktarTB2, 23000, "UAV", VEHICLE_CONDITION_UAV);
    ITEM(TMT_Kirpi_MRAP_GEN, 2040, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
