class vehicles_ws : vehicles_base
{
    ITEM(I_A_Truck_02_aa_lxWS, 6200, "AA", VEHICLE_CONDITION_AA);
    ITEM(APC_Wheeled_01_command_base_lxWS, 12720, "APC", VEHICLE_CONDITION_APC);
    ITEM(APC_Wheeled_01_atgm_base_lxWS, 32970, "APC", VEHICLE_CONDITION_APC);
    ITEM(O_APC_Tracked_02_30mm_lxWS, 32150, "APC", VEHICLE_CONDITION_APC);
    ITEM(O_APC_Wheeled_02_hmg_lxWS, 5860, "APC", VEHICLE_CONDITION_APC);
    ITEM(I_G_Offroad_01_armor_AT_lxWS, 6650, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(I_G_Offroad_01_armor_armed_lxWS, 4950, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(APC_Wheeled_01_mortar_base_lxWS, 26400, "ARTILLERY", VEHICLE_CONDITION_ARTILLERY);
    ITEM(B_ION_Heli_Light_02_dynamicLoadout_lxWS, 30200, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(B_ION_Heli_Light_02_unarmed_lxWS, 11000, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(I_Tura_ZU23_lxWS, 5000, "STATICAA", VEHICLE_CONDITION_STATICAA);
    ITEM(O_APC_Wheeled_02_unarmed_lxWS, 1740, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_G_Offroad_01_armor_base_lxWS, 1280, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_Truck_02_cargo_lxWS, 1700, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_Truck_02_flatbed_lxWS, 1700, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(C_Offroad_lxWS, 1280, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
};
